sudo: false

rvm:
  - ruby-head
  - 2.4.1
  - 2.3.4
  - 2.2
  - 2.1
  - 2.0.0
  - jruby-9.1.8.0

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cukes-devs@googlegroups.com
  webhooks:
    urls: # gitter
      - https://webhooks.gitter.im/e/dc010332f9d40fcc21c4
